### ISSUE TITLE
Invalid generated serial

### ISSUE THREAD

**Issue by diorcety** [mrexodia/akt#4]
Thanks for you program it's really great.
I'm trying to unpack a program having 2 certificates. I have brute forced the syms(2h with opencl) but both doesn't generate a valid serial. Is there something different to do?

**Comment by mrexodia** [comment]
you probably have to replace the ECDSA parameters. There is a plugin for this.

**Comment by diorcety** [comment]
Thanks for the reply. Do you have a link/tutorial on the usage of these plugins?

**Comment by mrexodia** [comment]
No, but they should be easy to use and you are welcome to send a pull
request or edit the wiki if you figure a plugin out :)

**Comment by diorcety** [comment]
Okay, i succeeded using your tutorial on internet. But there is certainly another protection, because the process now duplicate and hangs. The removal key tool doesn't work either i had to revert to my previous VM snapshot in order to retry, without a better success
