### ISSUE TITLE
Key does not match any known certificate

### ISSUE THREAD

**Issue by scerazy** [mrexodia/akt#5]
Trying to get key for abandonware, yet getting this error in a log when trying to use it

**Comment by mrexodia** [comment]
What's the abandonware?

**Comment by scerazy** [comment]
https://en.wikipedia.org/wiki/Abandonware

**Comment by mrexodia** [comment]
I'm well aware of what abandonware is, I'm asking what the software is that
you consider abandoned.

**Comment by mrexodia** [comment]
```
pirate
B939-6311-C244-5AC2
```
