### ISSUE TITLE
oth2 option won't accept 5 digital input

### ISSUE THREAD

**Issue by banxian** [mrexodia/akt#6]
I analysted a key (name: DS-15000053 serial: 000KVE-6KB7H6-4R2YRJ-VUKNUZ-QE400U-RMB2RX-J642MM) with Short V3 Level3 and got a oth2 value: 42399, and oth0/oth1 is 15 and zero.
when I copy oth2 to keygen tab, I found the input field only can accept 4 decimal numbers, not 5, nor hex.
is there something wrong in analyst or keygen tab?
I filled Sym, Y, Prv from a cert brute force result, and leave keystring/template empty.

**Comment by mrexodia** [comment]
Should be fixed with #8
