### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by acidmang** [mrexodia/akt#7]
If "OnTop" is selected when AKT exits, state is saved.  Launching AKT again will set "OnTop" checkbox as checked (expected) but AKT doesn't stay the top window.

**Comment by mrexodia** [comment]
Just tested, but works fine here.

**Comment by acidmang** [comment]
Figures. Not a big deal. :)

Nice to hear from ya, hope all is well.

Btw x64 debug is fantastic!
